apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-mq
spec:
  workspaces:
  - name: source
  params:
  - name: qm-template-path
    type: string
    description: The path where the Queue Manger template is
  - name: image
    description: image name of the MQ instance
    type: string
  - name: deployment-properties-path
    type: string
    description: The path where the deployment properties is located
  - name: mq-server-key-cert-secret
    type: string
    description: Name of the secret containing the MQ cert in the namespace where MQ is being deployed
  - name: ca-cert-secret
    type: string
    description: Name of the secret containing the CA cert in the namespace where MQ is being deployed
  - name: mq-server-cert-key
    type: string
    description: Name of the secret containing the MQ cert in the namespace where MQ is being deployed
  - name: mq-server-key-key
    type: string
    description: Name of the secret containing the MQ cert in the namespace where MQ is being deployed
  - name: ca-cert-key
    type: string
    description: Name of the secret containing the CA cert in the namespace where MQ is being deployed
  - name: tracing_ns
    type: string
    description: Namespace of the tracing Ops Dashboard to use
  steps:
    - name: apply-qm-template
      image: quay.io/openshift/origin-cli:latest
      workingDir: /workspace/source
      command: ["/bin/bash", "-c"]
      args:
        - |-
          echo Applying template $(params.qm-template-path)
          
          oc process -f $(params.qm-template-path) \
            --param IMAGE=$(params.image) \
            --param-file $(params.deployment-properties-path) \
            -p MQ_SERVER_KEY_CERT_SECRET=$(params.mq-server-key-cert-secret) \
            -p CA_CERT_SECRET=$(params.ca-cert-secret) \
            -p CA_CERT_KEY=$(params.ca-cert-key) \
            -p MQ_SERVER_KEY_KEY=$(params.mq-server-key-key) \
            -p MQ_SERVER_CERT_KEY=$(params.mq-server-cert-key) \
            -p TRACING_NS=$(params.tracing_ns) \
             | oc apply -f -

    - name: check-for-stateful-set
      image: quay.io/openshift/origin-cli:latest
      workingDir: /workspace/source
      command: ["/bin/bash", "-c"]
      args:
        - |-
          sscount="0"
          maxsscount="60"

          echo "May sleep for up to 10 minutes to wait for stateful set to be created"

          # Source in environment variables from file to get release name
          source $(params.deployment-properties-path)

          echo "Release is: $RELEASE_NAME"

          while [ $sscount -lt $maxsscount ]
          do
            statefulset_name=`oc get StatefulSet --selector=app.kubernetes.io/instance=$RELEASE_NAME -o custom-columns=:metadata.name --no-headers`
            echo "Stateful set is : $test"
            if [[ -z ${statefulset_name} ]]
            then
                if [ "$sscount" -eq $(($maxsscount -1)) ]
                then
                  echo "Stateful set not ready. After $sscount attempts."
                  exit 1
                fi
                echo "Stateful set not ready yet, sleep for 10 seconds."
                sleep 10;
            fi
            sscount=$[$sscount+1]
          done

          echo "MQ stateful set $statefulset_name for release $RELEASE_NAME created."