apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: mq-build-source
spec:
  params:
  - name: source-git-url
    value: $(body.repository.ssh_url)
  - name: source-repo-name
    value: $(body.repository.name)