apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: is-build-with-mq
spec:
  params:
    - name: is-source-repo-url
      value: git@github.ibm.com:cpat-int-samples/cpat-agile-integration-sample/create-customer-mq-soap-to-mq-json-v1.git
    - name: is-source-repo-private-key
      value: id_create-customer-details-v1

    - name: is-infra-repo-url
      value: git@github.ibm.com:cpat-agile-integration-sample/ace-infra.git
    - name: is-infra-repo-private-key
      value: id_agile-int-ace-infra

    - name: is-config-repo-url
      value: git@github.ibm.com:cpat-agile-integration-sample/ace-configurations.git
    - name: is-config-repo-private-key
      value: id_agile-int-ace-config

    - name: mq-source-repo-url
      value: git@github.ibm.com:cpat-agile-integration-sample/mq-source.git
    - name: mq-source-repo-private-key
      value: id_agile-int-mq-config

    - name: key-certs-secret-name
      value: ibm-client-key-certs
    - name: client-key
      value: ibm-client.key
    - name: client-cert
      value: ibm-client.crt
    - name: ca-cert
      value: ibm-ca.crt


  pipelineRef:
    name: is-build-with-mq

  serviceAccountName: pipeline

  workspaces:
    - name: shared-workspace
      persistentVolumeClaim:
        claimName: ace-cicd
