kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mq-role-for-pipeline
  namespace: mq-tb1
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log", "services"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]