apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mq-rolebinding-for-pipeline
  namespace: mq-tb1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mq-role-for-pipeline
subjects:
- kind: ServiceAccount
  namespace: ace-tb1
  name: pipeline
