# example run: oc process -f ssh-key-secret.yaml \
#                         -p NAME=eaglebank-mq-config \
#                         -p PRIVATE_KEY=$(base64 eaglebank-mq-config) \
#                         -p KNOWN_HOSTS=$(ssh-keyscan github.ibm.com | base64) | oc apply -f -

apiVersion: v1
kind: Template
metadata:
  name: secret
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    name: ${NAME}
    annotations:
      tekton.dev/git-0: github.ibm.com
  type: kubernetes.io/ssh-auth
  data:
    ssh-privatekey: ${PRIVATE_KEY}
    known_hosts: ${KNOWN_HOSTS}
parameters:
- name: NAME
- name: PRIVATE_KEY
  description: |
    Generate by running `base64 <path_to_file_containing_private_key>`
- name: KNOWN_HOSTS
  description: |
    Generate by running `ssh-keyscan github.ibm.com | base64`
    
