apiVersion: v1
kind: Template
metadata:
  name: tracing-list-r-b
objects:
- kind: RoleBinding
  apiVersion: rbac.authorization.k8s.io/v1
  metadata:
    name: tracing-list-rolebinding
    namespace: ${NAMESPACE_OD}
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: tracing-podlist-role
  subjects:
  - kind: ServiceAccount
    namespace: ${NAMESPACE_MQ}
    name: pipeline
  - kind: ServiceAccount
    namespace: ${NAMESPACE_ACE}
    name: pipeline
parameters:
  - name: NAMESPACE_OD
  - name: NAMESPACE_MQ
  - name: NAMESPACE_ACE