apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: image-updater
rules:
- apiGroups: 
    - "image.openshift.io"
  resources: 
    - "imagestreams"
    - "imagestreams/layers"
  verbs:
    - "*"
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - "*"