apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mq-builder-image-updater
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: image-updater
subjects:
- kind: ServiceAccount
  namespace: mq
  name: mq-builder
